name: CI/CD for Team A

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pipeline:
    uses: DevSecOps-AAU/ci-templates/.github/workflows/universal-pipeline.yml@main
    with:
      project-type: "python"
    secrets: inherit
